
- name: pipeline1 v2
  settings:
    country: "Colombia"
    add1: 1
    add2: 10
- name: pipeline1 v1
  settings:
    country: "Colombia"
    add1: 1
    add2: 2
- name: pipeline1 v0
  settings:
    country: "Colombia"
    add2: 2
    add3: 5